### ISSUE TITLE
新干员 崖心 角峰(给孑上buff的)  

### ISSUE THREAD

**Issue by fuyn101** [Funny-ppt/InfrastSim#2]
![图片](https://github.com/Funny-ppt/InfrastSim/assets/151902446/0909c97d-c8dd-4f76-aada-5659ae6b3613)
![图片](https://github.com/Funny-ppt/InfrastSim/assets/151902446/e0f46991-adc3-4165-946c-606ec51029b3)
我知道有银灰 但是我放不了两个银灰

**Comment by Funny-ppt** [comment]
昨日更新有崖心，今天更了角峰明天早上就可以用了，关闭
