### ISSUE TITLE
实际游戏内槐琥吃不到砾的薇薇安娜的加成

### ISSUE THREAD

**Issue by AQian22** [Funny-ppt/InfrastSim#3]
![砾1](https://github.com/Funny-ppt/InfrastSim/assets/154042727/e0253d46-594b-438c-b962-5c6014eb9eeb)
![砾2](https://github.com/Funny-ppt/InfrastSim/assets/154042727/4a2fc86d-fa51-4571-87b4-09882c874320)

中枢有VVAN+凯尔希

**Comment by Funny-ppt** [comment]
槐琥只计算本站成员效率。应该是计算了清流的问题。

**Comment by Funny-ppt** [comment]
![image](https://github.com/Funny-ppt/InfrastSim/assets/48616775/f143e8c1-d61c-4121-b885-5fe14bd00c48)

**Comment by Funny-ppt** [comment]
麻烦确认一下孑和清流的交互

**Comment by Funny-ppt** [comment]
sorry，脑子傻了，哎哟，我马上修复。请忽略上面第三条回复
