### ISSUE TITLE
按照干员名字的字数 排序 

### ISSUE THREAD

**Issue by fuyn101** [Funny-ppt/InfrastSim#4]
![图片](https://github.com/Funny-ppt/InfrastSim/assets/151902446/29c806ef-293d-4ba0-b52b-3dc7fd5f3483)

例如：
![图片](https://github.com/Funny-ppt/InfrastSim/assets/151902446/9dffbf0e-66c5-4138-b31b-2d92a72ad6cc)

**Comment by Funny-ppt** [comment]
参见 #5
