### ISSUE TITLE
能不能把耗电量电算出来

### ISSUE THREAD

**Issue by fuyn101** [Funny-ppt/InfrastSim#5]
![图片](https://github.com/Funny-ppt/InfrastSim/assets/151902446/14950f92-cf71-4bfa-8a84-4a343b22159e)
可以放在在这个地方

**Comment by Funny-ppt** [comment]
UI的建议最好提到隔壁InfrastSimUI仓库；UI短期应该不会更新（等我放假了会有很多大更新）

**Comment by Funny-ppt** [comment]
要求已经记录了，这边是模拟器内核仓库所以先关了
